// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgytixshskvtxekxmngs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpneXRpeHNoc2t2dHhla3htbmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjkzODUsImV4cCI6MjA2NTUwNTM4NX0.mKA1jIfv-wpaOrTDD8nbagw0c0s7SMuqmAgcHOgvPXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);